
spring:
  application:
    name: dubbo-provider

#dubbo:
#  application:
#    name: provider
#
#
#
#  registry:
#    address: zookeeper://127.0.0.1:2181
#
#  scan:
#    base-packages: com.zsx.service


# 不能这么配置
#dubbo:
#  application:
#    name: springboot-dubbo-provider1
#  registry:
#    address: zookeeper://127.0.0.1:2181


# 自定义配置
zsx:
  dubbo:
    registry:
      address: zookeeper://127.0.0.1:2181